### PR TITLE
Dockerfile.base: add aria2

### PR DESCRIPTION
**Pull request by PolynomialDivision**
OpenWrt now supports aria2c:
https://github.com/openwrt/openwrt/commit/d391236269314a759acb7dfb7ec01ccaa0e0b32c

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
ping @Ansuel

**Comment by ynezz** [comment]
> OpenWrt now supports aria2c:

Does this necessarily mean, that everyone should start using it? BTW is it really ready for prime time yet? Shouldn't it be first enabled in CI container to see how it goes? IIUC then the purpose of base containers is well, being minimal, so if that is still the case, shouldn't the removal of similar tools, wget and curl be considered as well?

**Comment by PolynomialDivision** [comment]
Okay, lets postpone it. :)

**Comment by aparcar** [comment]
Is aria2 an advantage regarding speed to the current solution?

**Comment by aparcar** [comment]
I [reworked the Dockerfiles](https://github.com/openwrt/docker/blob/master/Dockerfile.unify#L3) so they depend on the Buildbot images we're using. This PR should therefore add the tool to the Buildbot images instead.

**Comment by Ansuel** [comment]
@aparcar btw in having fun with CI on the main repo, in an effort to reduce the image to small stuff, I notice we can use minideb container instead of full debian https://github.com/Ansuel/openwrt/commit/2a942ed2982692f21e507f620ce5b1687f22c76f

It's widely used so I can be an idea.

**Pull request closed without merging**
